
export const MockData = [
    {
        archetypeTitle: "Sister-Hospitaler",
        archetypeSpecies: "Human",
        experiencePointCost: "24",
        keywords: "Imperium, Adeptus Ministorum, Adepta Sororitas, [Order]",
        attributes: "Willpower 3, Intellect 3",
        skills: "Medicae 1, Scholar 1",
        strength: "0",
        toughness: "0",
        agility: "0",
        willpower: "3",
        intellect: "3",
        fellowship: "0",
        speed: "0",
        ability: "Loyal Compassion",
        wargear: "Sororitas Power Armour, Chirugeons's Tools, Chain Bayonet (wrist mounted), Laspistol, Sororitas Vestments, Copy of the 'Rule of the Sororitas'"
    },
    {
        archetypeTitle: "Ministorum Priest",
        archetypeSpecies: "Human",
        experiencePointCost: "12",
        keywords: "Imperium, Adeptus Ministorum",
        attributes: "Willpower 3",
        skills: "Scholar 1",
        strength: "0",
        toughness: "0",
        agility: "0",
        willpower: "3",
        intellect: "0",
        fellowship: "0",
        speed: "0",
        ability: "Fiery Invective",
        wargear: "Chainsword, Laspistol, Rosarius, Knife, Ministorum Robes, Missionary Kit"
    },
    {
        archetypeTitle: "Imperial Guardsmen",
        archetypeSpecies: "Human",
        experiencePointCost: "6",
        keywords: "Imperium, Astra Militarum",
        attributes: "None",
        skills: "Ballistic Skill 2",
        strength: "0",
        toughness: "0",
        agility: "0",
        willpower: "0",
        intellect: "0",
        fellowship: "0",
        speed: "0",
        ability: "Look out sir!",
        wargear: "Flak Armour, Lasgun, Knife, Munitorum issue mess kit, Grooming Kit, " +
            "A copy of the 'Imperial Infantryman's Uplifting Primer, 3 ration packs"
    },
    {
        archetypeTitle: "Inquisitor Acolyte",
        archetypeSpecies: "Human",
        experiencePointCost: "6",
        keywords: "Imperium, Inquisition, [Any], [Ordo]",
        attributes: "None",
        skills: "Increase a Skill of your choice to 2",
        strength: "0",
        toughness: "0",
        agility: "0",
        willpower: "0",
        intellect: "0",
        fellowship: "0",
        speed: "0",
        ability: "Inquisitorial Decree",
        wargear:"Flak Armour, Any two IMPERIUM weapons with a Value of 5 or less and a " +
            "Rarity of Uncommon or lower, Symbol of Authority"
    },
    {
        archetypeTitle: "Inquisitor Sage",
        archetypeSpecies: "Human",
        experiencePointCost: "16",
        keywords: "Imperium, Adeptus Administratum, Inquisition, [Ordo]",
        attributes: "Intellect 3",
        skills: "Scholar 2",
        strength: "0",
        toughness: "0",
        agility: "0",
        willpower: "0",
        intellect: "3",
        fellowship: "0",
        speed: "0",
        ability: "Administratum Records",
        wargear: "Administratum Robes, Laspistol, Knife, Auto Quill, Data-Slate, 3 Scrolls of Ancient Records"
    },
    {
        archetypeTitle: "Ganger",
        archetypeSpecies: "Human",
        experiencePointCost: "2",
        keywords: "Scum, [Any]",
        attributes: "None",
        skills: "Cunning 1",
        strength: "0",
        toughness: "0",
        agility: "0",
        willpower: "0",
        intellect: "0",
        fellowship: "0",
        speed: "0",
        ability: "Scrounger",
        wargear: "A knife or a Sword, Bedroll, Canteen, Gang coulours, any one of the following: " +
            "a Laspistol or an Autopistol or a Hand Cannon or a Stubber"
    },
    {
        archetypeTitle: "Corsair",
        archetypeSpecies: "Aeldari",
        experiencePointCost: "16",
        keywords: "Aeldari, Anhrathe, [Coterie]",
        attributes: "Agillity 3",
        skills: "Athletics 2",
        strength: "0",
        toughness: "0",
        agility: "3",
        willpower: "0",
        intellect: "0",
        fellowship: "0",
        speed: "0",
        ability: "Dancing on the Blade's Edge",
        wargear: "Corsair Armour, Shuriken Pistol, Lasblaster, Spirit Stone, 3 Plasma Grenades, Void Suit"
    },
    {
        archetypeTitle: "Ork Boy",
        archetypeSpecies: "Ork",
        experiencePointCost: "26",
        keywords: "Ork, [Clan]",
        attributes: "Strength 3, Toughness 3",
        skills: "Weapon Skill 2",
        strength: "3",
        toughness: "3",
        agility: "0",
        willpower: "0",
        intellect: "0",
        fellowship: "0",
        speed: "0",
        ability: "Get Stuck In",
        wargear: "Shoota, Slugga, Choppa, Ripped clothes"
    }
];